[build]
providers = ["python"]

[build.env]
NIXPACKS_PATH = "backend"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.start]
cmd = "python3 main.py"
