[build]
providers = ["python"]

[build.env]
NIXPACKS_PATH = "backend"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip install -r backend/requirements.txt"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
